<a href="https://colab.research.google.com/github/jeffersonramelo/M-TODOS-QUANTITATIVOS/blob/main/frequencias2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

#lendo os dados
dados = pd.read_csv("/content/Exercício 02_dados_prazo_recebimento.csv")
dados

    Prazo_recebimento
0                   4
1                   9
2                  12
3                  16
4                  19
5                  24
6                  29
7                   6
8                  10
9                  13
10                 17
11                 20
12                 25
13                 30
14                  7
15                 11
16                 14
17                 18
18                 21
19                 26
20                 31
21                  4
22                  8
23                 15
24                 19
25                 22
26                 27
27                 28
28                  7
29                 10
30                 13
31                 17
32                 20
33                 23
34                 29
35                  6
36                 11
37                 14
38                 18
39                 21
40                 25
41                 30
42                  9
43                 12
44                 15
45                 16
46                 22
47                 24
48                 32

In [10]:
#isolar a coluna que formará a tabela de frequências
x = dados["Prazo_recebimento"]
len(x)

#ordenação em ROL
y = x.sort_values()
y

0      4
21     4
7      6
35     6
28     7
14     7
22     8
1      9
42     9
8     10
29    10
15    11
36    11
43    12
2     12
30    13
9     13
16    14
37    14
44    15
23    15
45    16
3     16
10    17
31    17
38    18
17    18
24    19
4     19
11    20
32    20
18    21
39    21
25    22
46    22
33    23
47    24
5     24
12    25
40    25
19    26
26    27
27    28
6     29
34    29
13    30
41    30
20    31
48    32
Name: Prazo_recebimento, dtype: int64

In [16]:
# Frequência simples absoluta
fs = y.value_counts().sort_index()

fs

# Frequência simples relativa (%)
fsr = (fs / len(x)) * 100

fsr

#Frequência acumulada
fa = fs.cumsum()

fa

#Frequência relativa acumulada (%)
far = (fa / len(x)) * 100

far

Prazo_recebimento
4       4.081633
6       8.163265
7      12.244898
8      14.285714
9      18.367347
10     22.448980
11     26.530612
12     30.612245
13     34.693878
14     38.775510
15     42.857143
16     46.938776
17     51.020408
18     55.102041
19     59.183673
20     63.265306
21     67.346939
22     71.428571
23     73.469388
24     77.551020
25     81.632653
26     83.673469
27     85.714286
28     87.755102
29     91.836735
30     95.918367
31     97.959184
32    100.000000
Name: count, dtype: float64

In [20]:
#juntar todas as frequências

tabela = pd.DataFrame({"fsimples": fs, "fsimples%": fsr, "facumulada": fa, "facumulada%": far})
tabela
#

                   fsimples  fsimples%  facumulada  facumulada%
Prazo_recebimento
4                         2   4.081633           2     4.081633
6                         2   4.081633           4     8.163265
7                         2   4.081633           6    12.244898
8                         1   2.040816           7    14.285714
9                         2   4.081633           9    18.367347
10                        2   4.081633          11    22.448980
11                        2   4.081633          13    26.530612
12                        2   4.081633          15    30.612245
13                        2   4.081633          17    34.693878
14                        2   4.081633          19    38.775510
15                        2   4.081633          21    42.857143
16                        2   4.081633          23    46.938776
17                        2   4.081633          25    51.020408
18                        2   4.081633          27    55.102041
19                        2   4.081633          29    59.183673
20                        2   4.081633          31    63.265306
21                        2   4.081633          33    67.346939
22                        2   4.081633          35    71.428571
23                        1   2.040816          36    73.469388
24                        2   4.081633          38    77.551020
25                        2   4.081633          40    81.632653
26                        1   2.040816          41    83.673469
27                        1   2.040816          42    85.714286
28                        1   2.040816          43    87.755102
29                        2   4.081633          45    91.836735
30                        2   4.081633          47    95.918367
31                        1   2.040816          48    97.959184
32                        1   2.040816          49   100.000000

In [24]:
#organizada em classes de frequências

import numpy as np

z = np.sqrt(len(x))
z

np.float64(7.0)